### ISSUE TITLE
Change default id or path Volume argument

### ISSUE THREAD

**Issue by organisciak** [massivetexts/htrc-feature-reader#11] opened 2020-01-08 23:33 UTC
With the large updates soon to be sent to production, @bmschmidt recommended swapping the default argument for a Volume or FeatureReader to be 'id', rather than 'path' (https://github.com/htrc/htrc-feature-reader/issues/32). This is what's used for the online loading, or can be used (in the future) for finding a file in a pairtree.

In other words, this is what's currently possible

```
Volume(id='htid')
Volume(path='/path/to/ef/file')
Volume('/path/to/ef/file')
```

where the proposed change would make the third option invalid, in favor of these valid options:

```
Volume(id='htid')
Volume(path='/path/to/ef/file')
Volume('htid')
```

Seemingly small, but I'd like to know what @elfdickson thinks.

Argument against it is that it confuses existing users and obfuscates a file-based mode of interaction, the argument for it is that IDs are a more sensible way of thinking of the data for beginners. I'd add that the pairtree format isn't *meant* to be treated as a full file structure, and is intended as a behind-the-scenes way of storing files that can be recalled by ID on the front end. The default, to load the file by HTTP straight from HTRC, is also easier for the end-user, though I wouldn't want users to think it's the primary way given the speed cost on their end and bandwidth cost on HTRC's end.

**Comment by bmschmidt** [comment] 2020-01-09 19:28
There's also--as we're finding--a reproducibility/portability issue here. Code that addresses volumes using `path` requires a local filesystem setup, while code that addresses using `id` should be more robust to different settings by changing a line at the top of the script without having to rip up the internals when running on different machines.

**Comment by bmschmidt** [comment] 2020-01-09 20:13
The compatible way to handle this would probably be to make the change to both FeatureReader and to Volume and to use a sentinel to break it in slowly.

Next release:
 
```python
Volume(_sentinel = None, id = "foo", path = "foo/bar.gz"):
    if sentinel is not None and not config.get("treat_unnamed_args_as_paths"):
        raise DeprecationWarning("""You have passed an unnamed argument. In the next major release, this will be treated as an ID. Please change your code to use an id or call f"Volume(path={_sentinel})", 
or type htrc_features.config.set(treat_unnamed_args_as_paths = True) to change the options for this project.""")
```

Some future release: drop the sentinel, raise a DeprecationError.

````python
Volume(id = "foo", path = "foo/bar.gz"):
    if config.get("treat_unnamed_args_as_paths"):
        raiseDeprecationWarning("""Passing unnamed paths to `Volume` or `FeatureReader` is no longer supported.""")
```

**Comment by bmschmidt** [comment] 2020-01-17 20:30
The above issue proposal is fine.

But another option is:

1. Use a sentinel to catch unnamed arguments silently.
2. Use a regex to figure out if it's a path or an id. In practice, this will work 99% of the time because it will end with `.json.bz2` or something very similar. I think it's OK to break the other versions.
3. If it's an ID, use some set of defaults TBD.
4. If it's a path, set id = _sentinel and use a `PathIdResolver` method. Send a warning that in future versions, users should set `path` explicitly.

In general, have `Volume(path = path)` be a shortcut for `Volume(id = path, id_resolver = PathIdResolver)`.

**Comment by rdubnic2** [comment] 2020-01-22 18:58
Hi @organisciak: Eleanor asked me to review the proposed change and respond with thoughts. Sorry for the delay, it took me a bit to find my way to this fork and issue. 

I think changing the default argument for volume to ID makes a lot of sense. The only drawback I could think of is the exact one you point out--that it obfuscates a typical model of loading files in through path. But I also agree with @bmschmidt that this is more flexible. I also think it's easier syntax for a novice coder. This change has little to no impact on our current notebooks and docs, we believe. Let me know if you have other questions on this!

**Comment by bmschmidt** [comment] 2020-02-10 05:36
Closing with https://github.com/massivetexts/htrc-feature-reader/pulls.

So the ultimate route is to, indeed, put `id` first in both readers, but to quickly check if there's a '.json' or '.bz2' at the end and, if so, to load it using a filepath protocol. 

That means there's no need to aggressively deprecate.

The only places this should cause any issues, I think, is if someone was using an extremely weird filenaming protocol. Since HTRC distributes features with files, I can't really imagine this happening.

**Closed as completed by bmschmidt** 2020-02-10 05:36 UTC
